public class exceptiondemo {
 public static void main(String[] args) {
     try {
     int a=10,b=0;
     int result=a/b;//division by zero
     System.out.println("result:"=result);
     }
catch(arthimatic)
     e) {
     }
 }


[1,2,3,4,5,6,9] 
 i        